import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'models/user_profile.dart';
import 'models/daily_log.dart';
import 'models/cycle_data.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive for local, privacy-first storage
  await Hive.initFlutter();
  
  // Register Adapters (these will be generated by build_runner)
  Hive.registerAdapter(UserProfileAdapter());
  Hive.registerAdapter(DailyLogAdapter());
  Hive.registerAdapter(CycleDataAdapter());
  
  // Open Boxes
  await Hive.openBox<UserProfile>('userProfileBox');
  await Hive.openBox<DailyLog>('dailyLogBox');
  await Hive.openBox<CycleData>('cycleDataBox');

  runApp(const ProviderScope(child: IrmaApp()));
}

class IrmaApp extends StatelessWidget {
  const IrmaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Irma - CycleSense',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFB4A8D3), // Calming pastel purple
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        // Minimal, calm font to support the "Gentle Design" principle
        fontFamily: 'Inter', 
      ),
      home: const Scaffold(
        body: Center(
          child: Text('Irma App Initialization'),
        ),
      ),
    );
  }
}
